language: generic

sudo: required
services:
  - docker
before_install:
  - docker build -t dhaponov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dhaponov/react-test npm test

after_success:
  - docker build -t dhaponov/multi-client ./client
  - docker build -t dhaponov/multi-nginx ./nginx
  - docker build -t dhaponov/multi-server ./server
  - docker build -t dhaponov/multi-worker ./worker

# take these images and push them to docker-hub

# for this need to log in to the docker CLI:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push dhaponov/multi-client
  - docker push dhaponov/multi-nginx
  - docker push dhaponov/multi-server
  - docker push dhaponov/multi-worker